### ISSUE TITLE
Family Share

### ISSUE THREAD

**Issue by 1051t** [Kemmey/Kemmey-TeslaWatch-Public#51] opened 2020-07-09 18:57 UTC
Application will not family share.

**Comment by Kemmey** [comment] 2020-07-09 19:42
Duplicate of https://github.com/Kemmey/Kemmey-TeslaWatch-Public/issues/46

**Comment by Kemmey** [comment] 2020-07-09 19:43
The app is marked as supporting family sharing - but it is not something I have control over, except allowing it.

Apple takes a 30% cut of all proceeds for their part in maintaining the infrastructure. I'm not sure they live up to their end of that bargain.

Please contact AppStore support and have them fix their infrastructure!

I'm sorry I can't be of more help - but the AppStore infrastructure is completely outside of my control.

**Closed by Kemmey** 2020-07-09 19:42 UTC

**Comment by 1051t** [comment] 2020-07-09 20:04
Thanks, great app

Mitch
