### ISSUE TITLE
Watch apps shows different range to Tesla app

### ISSUE THREAD

**Issue by Panthium** [Kemmey/Kemmey-TeslaWatch-Public#52] opened 2020-07-09 21:56 UTC
Tesla App and car shows 210m range
Watch app shows 263m range
Tesla is Facelift 2016 model S P90DL / MCU1

**Comment by Kemmey** [comment] 2020-07-10 05:06
Duplicate of https://github.com/Kemmey/Kemmey-TeslaWatch-Public/issues/40

The title is misleading - the discussion contains the details. 

Fixed in 1.0.6 beta. 

Not yet shipped to AppStore

**Closed** 2020-07-10 05:06 UTC
Labels: ShippedInBeta, bug, duplicate

**Comment by Panthium** [comment] 2020-07-14 00:14
Thanks.

I tried using Tesla watch app without phone being near and it doesn't work. Lots of messages with countdown timer on the app screen, but no commands reached the car.

Is this expected behaviour?

Note I have Gen4 watch with data simm activated.

**Comment by Kemmey** [comment] 2020-07-14 05:16
No, that is not expected bahaviour. 

The app works absolutely fine over cellular and is in no way dependent on your phone. 

But the watch often takes a long time to roam away from Bluetooth and get a cellular connection. It might just not have managed to connect yet. 

Please try again with your cellular watch, but verify that the watch does have internet connectivity, by for instance trying out a Siri command or sending a message.
