### ISSUE TITLE
phone and watch showing different battery charge

### ISSUE THREAD

**Issue by Skye00023** [Kemmey/Kemmey-TeslaWatch-Public#66] opened 2020-07-23 13:42 UTC

**Comment by Kemmey** [comment] 2020-07-23 14:03
Please validate age of data on watch and phone. Best guess is that one of the data sets are outdated.

**Comment by Skye00023** [comment] 2020-07-23 14:56
Hi Kim,

iPhone and car were showing 250miles and watch 325 85%

I’ll try updating software but car only ever charges to 309

Kenny

On 23 Jul 2020, at 15:04, Kim Hansen <notifications@github.com> wrote:

﻿

Please validate age of data on watch and phone. Best guess is that one of the data sets are outdated.

**Comment by Kemmey** [comment] 2020-07-23 15:43
@Skye00023 Ah - that makes sense then - I figured you meant percent charge, not range. 

Range is fixed in current beta - will ship in 1.0.6 soon. 

It boils down to the fact that model 3 and y cannot choose which range so show - it is always the ideal factory range. Which is what the app shows. For model s and x you can change that to estimated real-world range. Which I presume you have. This is fixed in 1.0.6 where the app will pick your configuration from the car and show accordingly.

**Comment by Kemmey** [comment] 2020-07-23 15:44
Duplicate of https://github.com/Kemmey/Kemmey-TeslaWatch-Public/issues/52

**Closed** 2020-08-12 20:16 UTC
Labels: duplicate
