### ISSUE TITLE
Not showing ideal range

### ISSUE THREAD

**Issue by tomsteenbakkers** [Kemmey/Kemmey-TeslaWatch-Public#87] opened 2020-08-09 19:30 UTC
Why is the watch app not showing the ideal range. It now shows the rated range which is different from what the car and app is reporting.

**Comment by Kemmey** [comment] 2020-08-09 19:40
Duplicate of https://github.com/Kemmey/Kemmey-TeslaWatch-Public/issues/40

**Closed** 2020-08-09 19:40 UTC
Labels: ShippedInBeta, duplicate

**Comment by tomsteenbakkers** [comment] 2020-08-09 19:57
Sorry did read the closed items. If this will be in the next update i will be buying this app. 

Suggestion: the complications of Automate are very nice and useful especially the battery gauge.

**Comment by Kemmey** [comment] 2020-08-09 20:39
I'm very confused. 

Are you running the latest beta but the ranges are still wrong, or are you running the App Store version?

The complications already show battery as gauges - how would you like them improved?

**Comment by tomsteenbakkers** [comment] 2020-08-09 20:52
I'm running the App Store version. 

AutoMate uses the following complications. The battery is shows including the percentage which is really a nice feature. I enclosed also a screenshot where you can see the difference between rated and ideal. In the Netherlands the differ quit a lot.

![image](https://user-images.githubusercontent.com/24613800/89741591-c72e4480-da92-11ea-8aa9-e919774238d6.jpeg)

![image](https://user-images.githubusercontent.com/24613800/89741594-cd242580-da92-11ea-8eaa-ff7ab556432c.jpeg)

![image](https://user-images.githubusercontent.com/24613800/89741599-d3b29d00-da92-11ea-8fb6-20f00c763d5e.jpeg)

**Comment by Kemmey** [comment] 2020-08-09 21:01
Ok, rated and ideal will be picked up from car now so they are in sync with Tesla app. I will only show one or the other. For model 3 and Y they cannot be changed. Only model S and X can change those values in their settings panels. 

The complications seems very similar to mine? Only difference I can spot is the three digit modular circular - I was not able to reliably get three digits to stick - it varied with which digits if I would get "111" or "44...". So I gave up and only show range in the complications that I tested would actually show three digits reliably. The rest always show percent, no matter what the vehicle is set to.

**Comment by tomsteenbakkers** [comment] 2020-08-09 21:17
Great that the range is displayed based on a setting.

The complication look the pretty much the same. It's nice that you can see the range and the battery level in one complication especially in an Infograph. Since I never charge to 100% I do not have the problem you described 🤗

**Comment by Kemmey** [comment] 2020-08-10 19:59
Range when shown in miles or kilometers will easily exceed two digits... So really depends on user preference. I always keep my car set to SoC as percent, as range doesn't make any sense - it might rain one day and range is halved - it might be calculated from a rainy day but it's sunny so range is doubled. It's just way too hard to calculate properly to be useful. But again - that's my preference - which is why the app will read the car configuration and act accordingly.
