### ISSUE TITLE
loading

### ISSUE THREAD

**Issue by TeslaRen** [Kemmey/Kemmey-TeslaWatch-Public#120] opened 2020-09-04 18:45 UTC
The app has been "loading" for seven day and nothing is operational. Should I uninstall and reinstall?

**Comment by bill99999** [comment] 2020-09-17 15:25
I just installed this app on my Watch after updating to Watch OS 7.0 and all I get after logging in is the “Model 3 Loading...” message. It never loads, even though the Tesla app is running on my iPhone and the car is awake.

**Comment by Kemmey** [comment] 2020-09-17 21:33
@bill99999 There are a few watchOS 7 issues that I'm currently working on. One is in the vehicle chooser, when you tap the name of your vehicle - that will never finish loading. Or rather - it will never update the view. Just tap on your vehicle name again and you should be returned to the main screen where the app should work quite well. 

If that is not the case, please attach screenshot.

**Comment by Kemmey** [comment] 2020-09-17 21:34
@TeslaRen has this issue been open for two weeks without an answer?! Please don't let it be so - let me know if you're still not receiving updates from the car.

**Comment by bill99999** [comment] 2020-09-17 23:21
Your app eventually started working today--perhaps because I had the main screen showing (?). Thanks!

- Bill

**Comment by TeslaRen** [comment] 2020-09-18 02:24
No worries. It was most likely user error! The only issue I seem to have is beta testing. I tried the links you sent but I need a code.  Waaa.

**Comment by Kemmey** [comment] 2020-09-18 05:06
@bill99999 @TeslaRen I'm glad to hear both of your issues are solved :-D 

You can join the public TestFlight if you want a head start on watchOS 7 compatibility - though the build is not up yet, it will be soon. 

There's no special code - just tap the link once to install the TestFlight app, then come back and tap the link again with the TestFlight app installed, then the same link should open the TestFlight app and allow you to join. 

https://testflight.apple.com/join/FdzFOLZv

**Comment by bill99999** [comment] 2020-09-18 16:20
Thanks, Kim, I have just installed the latest build via TestFlight.

I have a question about the "remote start" feature. The problem I would like to solve with your Watch app is that, for the last six weeks or so, I have had to pull out my iPhone and open its Tesla app before I can start driving (otherwise it wants a key card). I never had to do this before, but a Tesla Service technician claims it is a new security feature. I know I can set the iPhone app to run constantly in the background, but I have tried not to have background apps running at all on my iPhone.

I tried using Remote Start on your Watch app, and that did work. However, the car did not lock automatically when I walked away. Does Remote Start mean no key card or iPhone app is required, so anyone who can get into the car can drive it? Since I live in a city, this would not be a good idea in my case. Is there any way your app could, when tapped, cause the Tesla to assume the iPhone app is open and let me drive the car? This would retain the security of the car and preserve auto-locking, relying on the fact that I have logged into my Apple Watch in order to use your app (sort of like ApplePay).

Thanks for considering this.

- Bill

**Comment by Kemmey** [comment] 2020-09-18 19:15
@bill99999 I can solve half of your problem. In the TestFlight beta version, there's a new toggle under remote start, to auto activate when tapping the unlock button in the watch app. If you activate that, all you have to do, is bring up the app on your watch, tap the padlock and the app will unlock your car, unlock your chargeport so you can unplug and activate remote start so you can drive away - all with one single tap :-D 

But if you're force-quitting your Tesla app on your iPhone, you will have to manually remember to lock your car, as walk-away lock require the Tesla app to run in background. And it can't be done automatically with the watch - you have to tap the lock button manually. 

Btw, you REALLY should not be force quitting apps on your iPhone - you'll be working against the operating system - you'll be wasting MORE battery as all apps will have to cold start each time. The system automatically sleeps apps that have not run for a few seconds, but if you force quit, the system wipes the resume data. Use the operating system as intended, and trust it to run your phone efficiently - that's what it's made to do. Your battery will last longer - both in battery life day to day, but also lifetime in years.

**Comment by bill99999** [comment] 2020-09-18 19:24
OK, that seems counter-intuitive, but I'll try it. Thanks for the help.

BTW, I'm not sure how to report an issue in TestFlight. I have two main control rows showing in my Watch app. The first row looks fine, but the second row seems odd. It is listed as "open trunk", "unlock port", and "open port." The icons seem to be an open trunk, a lightning bolt inside a circle, and a thermometer in front of a snowflake, respectively. I would have guessed that the last icon, at least, would defrost the car or some such (?). Sorry if I'm being obtuse.

- Bill

**Comment by Kemmey** [comment] 2020-09-18 19:40
@bill99999 You just did report a TestFlight bug! Reporting here is perfect :-D 

I just reproduced your issue - and I get why that is confusing, but I tried to mitigate with an in-app description. Please read the small notice at the top of the controls reordering page. Basically, controls will shift based on availability - so looking at my controls below, the defrost action is actually the one being shown, as the other controls are currently unavailable, so they won't be shown. 

![image](https://user-images.githubusercontent.com/4688084/93638408-87df0600-f9f7-11ea-8b93-da93a1e61e70.png)
![image](https://user-images.githubusercontent.com/4688084/93638416-8ad9f680-f9f7-11ea-99be-1ae4204cb6f7.png)

**Comment by bill99999** [comment] 2020-09-18 20:10
This is what I'm seeing in the settings page for the second row of controls:



This is what I see on the main page:


I think I understand what you're saying: The "unlock port" control is dimmed, so it's showing the icon for the next control down, which is "open port." The next two controls are also dimmed, so the final icon in the second row corresponds to the next undimmed control, which is "defrost."

I wonder if there is some other way to display this that would be a bit clearer. Could the dimmed control names move down below the list of undimmed names? Actually, I just succeeded in reading the gray fine print that explains what's going on. Sorry, I'm developing cataracts and gray text is almost invisible to me.  BTW, could the names scroll more slowly during control dragging? This was really hard for me. Just a thought.

Bill

**Comment by Kemmey** [comment] 2020-09-23 10:37
Fixed in released 1.0.7

**Closed** 2020-09-23 10:37 UTC

**Comment by TeslaRen** [comment] 2020-12-12 22:48
Hi Kim,

 

My iPhone app has stopped working. Message says that testing has ended. Can you help?

 

Thanks…Lauren

**Comment by Kemmey** [comment] 2020-12-12 22:55
Open TestFlight app and update to latest version. 

If it's completely gone, re-join here: https://testflight.apple.com/join/FdzFOLZv

**Comment by TeslaRen** [comment] 2020-12-12 23:20
Thank you so much. All is well in the world again. Is Siri now working ? I tried to get on the beta test but could not. Can I still be part of that?

**Comment by Kemmey** [comment] 2020-12-13 07:44
If you tap the link in previous message and open that in TestFlight and tap join, that is the beta test. It's continually updated. And with the most recent version of the TestFlight app you can even have it auto-update. 

Siri has four commands that work, but you have to enable the app with Siri in settings manually - because... Apple.

**Comment by Kemmey** [comment] 2020-12-13 07:46
See Siri instructions here: https://github.com/Kemmey/Kemmey-TeslaWatch-Public/issues/168#issuecomment-706531310

**Comment by TeslaRen** [comment] 2020-12-13 16:51
Thank you very much for always being responsive.
